[package]
name = "do-lang"
version = "0.1.0"
authors = ["iohub <cn.ydlme@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lalrpop-util = "0.16"
regex = "0.2.0"
llvm-sys = "60.0.3"
lazy_static = "1.3.0"
clap = "~2.33"

[build-dependencies]
lalrpop = "0.16"

